---
- name: Configuring VyOS networking via config.boot overwrite...
  become: false
  delegate_to: localhost
  block:
    - name: Templating raw VyOS tree configuration...
      ansible.builtin.template:
        src: config.boot.j2
        dest: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_config.boot
        mode: "0644"

    - name: Reading local rendered configuration...
      ansible.builtin.slurp:
        src: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_config.boot
      register: config_boot_file

    - name: Overwriting config.boot via Proxmox Guest Agent...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/file-write"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}"
        body:
          content: "{{ config_boot_file.content | b64decode }}"
          file: /config/config.boot
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"

    - name: Live-reloading VyOS configuration engine...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/exec"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}"
        body:
          command:
            - /bin/vbash
            - -c
            - 'sg vyattacfg -c "source /opt/vyatta/etc/functions/script-template && configure && load /config/config.boot && commit && exit"'
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"
      register: network_config_command

    - name: Including command run check task...
      ansible.builtin.include_tasks: command_run_check.yml