---
- name: Configuring VyOS networking via config.boot overwrite...
  become: false
  delegate_to: localhost
  block:
    - name: Templating raw VyOS configuration...
      ansible.builtin.template:
        src: config.boot.j2
        dest: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_config.boot
        mode: "0644"

    - name: Reading local rendered configuration...
      ansible.builtin.slurp:
        src: /tmp/{{ project_fullname | default('') }}_{{ inventory_hostname }}_config.boot
      register: config_boot_file

    - name: Overwriting config.boot via Proxmox Guest Agent...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/file-write"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}"
        body:
          content: "{{ config_boot_file.content | b64decode }}"
          file: /config/config.boot
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"

    - name: Adding test text file via Proxmox Guest Agent...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/file-write"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}"
        body:
          content: "{{ config_boot_file.content | b64decode }}"
          file: /config/config_boot_test.txt
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"

    - name: Adding test text file via Proxmox Guest Agent...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/file-write"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}"
        body:
          content: "test"
          file: /config/config_boot_test.txt
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"

    # Live reloading
    - name: Creating reload wrapper script locally...
      ansible.builtin.copy:
        dest: /tmp/vyos_live_reload.sh
        mode: "0644"
        content: |
          #!/bin/vbash
          if [ "$(id -g -n)" != 'vyattacfg' ] ; then
              exec sg vyattacfg -c "/bin/vbash $(readlink -f $0) $@"
          fi
          source /opt/vyatta/etc/functions/script-template
          configure
          load /config/config.boot
          commit
          exit

    - name: Uploading reload script to VyOS...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/file-write"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}"
        body:
          content: "{{ lookup('file', '/tmp/vyos_live_reload.sh') }}"
          file: /tmp/vyos_live_reload.sh
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"

    - name: Executing clean configuration live reload...
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ cfg_net_proxmox_node }}/qemu/{{ cfg_net_proxmox_vmid }}/agent/exec"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_defaults.api_user }}!{{ proxmox_defaults.api_token_id }}={{ proxmox_defaults.api_token_secret }}"
        body:
          command:
            - /bin/vbash
            - /tmp/vyos_live_reload.sh
        body_format: json
        validate_certs: "{{ proxmox_defaults.validate_certs }}"
      register: network_config_command

    - name: Including command run check task...
      ansible.builtin.include_tasks: command_run_check.yml